# Site settings
title: Working Copy blog
author: Anders Borum
email: anders@workingcopyapp.com
avatar: http://www.gravatar.com/avatar/0a9db816d346838428351503775e6d81.png
description: > # this means to ignore newlines until "baseurl:"
  This blog describes how Working Copy can be used for blogging and
  software development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http:/palmin.github.io/" # the base hostname & protocol for your site
twitter_username: palmin
github_username:  palmin

# Build settings
markdown: kramdown
